In [3]:
import numpy as np

## Проверим унитарную инвариантность некоторых матричных норм

In [60]:
n, m = 100, 10
A = np.random.randn(n, m)

In [61]:
Q, _ = np.linalg.qr(A)

In [62]:
Q.shape

(100, 10)

In [63]:
np.linalg.norm(Q.T @ Q - np.eye(m))

6.868433711681044e-16

In [65]:
A = np.random.randn(10, 200)
print(np.linalg.norm(A))
print(np.linalg.norm(Q @ A))

45.153942097406244
45.15394209740624


## Убедимся в эффективности умножения на матрицу Хаусхолдера за линейное время

In [66]:
def householder_matvec(v, x):
    return x - 2 * v * (v @ x)


In [67]:
n = 1000
v = np.random.randn(n)
v = v / np.linalg.norm(v)
x = np.random.randn(n)
%timeit householder_matvec(v, x)
%timeit (np.eye(n) - 2 * np.outer(v, v))  @ x

6.57 µs ± 185 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
5.9 ms ± 290 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## Проверим, что матрица Хаусхолдера, построенная по теореме, действительно зануляет все элементы вектора кроме первого

In [71]:
x = np.random.randn(5)
x

array([ 0.12411776, -1.29628581, -1.87237503, -1.16096815,  0.15905101])

In [91]:
e1 = np.zeros(5)
e1[0] = 1.

v = (x - e1 * np.linalg.norm(x)) / (-np.sqrt(2 * (x @ x - x[0] * np.linalg.norm(x))))
# print(v, -v, (x + e1 * np.linalg.norm(x)) / (np.sqrt(2 * (x @ x - x[0] * np.linalg.norm(x)))))
print(v @ v)
print(v)
householder_matvec(v, x)

1.0
[ 0.68978052  0.36645618  0.52931491  0.32820228 -0.04496325]


array([ 2.56411674e+00, -2.22044605e-16,  0.00000000e+00, -2.22044605e-16,
        2.77555756e-17])